### PR TITLE
Validate Value and ValueFromFieldPath are not nil

### LINKED ISSUE #23: nil pointer dereference when using type: FromCompositeFieldPath and omitting valueFromFieldPath
### What happened?

When adding a pipeline step that uses selector with FromCompositeFieldPath and omitting valueFromFieldPath, the function crashes with nil pointer dereference

```
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13e4292]

goroutine 7 [running]:
main.buildRequirements(0xc000244780, 0xc000225130)
        /fn/fn.go:140 +0x4d2
main.(*Function).RunFunction(0xc00040c7f0, {0xc0006800c0?, 0x499ae6?}, 0xc0006800c0)
        /fn/fn.go:57 +0x265
github.com/crossplane/function-sdk-go/proto/v1beta1._FunctionRunnerService_RunFunction_Handler({0x1506580?, 0xc00040c7f0}, {0x190c0a0, 0xc0001ee930}, 0xc00050c080, 0x0)
        /go/pkg/mod/github.com/crossplane/function-sdk-go@v0.2.0/proto/v1beta1/run_function_grpc.pb.go:104 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001b6e00, {0x190c0a0, 0xc0001ee690}, {0x1911900, 0xc0001f6680}, 0xc0000ec000, 0xc0000afb60, 0x23f39c0, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.61.0/server.go:1385 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc0001b6e00, {0x1911900, 0xc0001f6680}, 0xc0000ec000)
        /go/pkg/mod/google.golang.org/grpc@v1.61.0/server.go:1796 +0xfec
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        /go/pkg/mod/google.golang.org/grpc@v1.61.0/server.go:1029 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 24
        /go/pkg/mod/google.golang.org/grpc@v1.61.0/server.go:1040 +0x135
```

### How can we reproduce it?

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-environment-configs
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: pull-extra-resources
    functionRef:
      name: function-extra-resources
    input:
      apiVersion: extra-resources.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        extraResources:
          - kind: XCluster
            into: XCluster
            apiVersion: example.crossplane.io/v1
            type: Selector
            selector:
              maxMatch: 2
              minMatch: 1
              matchLabels:
                - key: type
                  type: FromCompositeFieldPath
                  value: cluster
```

### What environment did it happen in?
Function version: 0.0.3

### PR DESCRIPTION
**Pull request by etesami**
### Description of your changes

Fixes #23 

This PR adds validations to ensure proper field selection:

- When `ValueFromFieldPath` is selected, the `valueFromFieldPath` field is checked to ensure it is not `nil`.
- When `Value` is selected, the `value` field is verified to be non-`nil`.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Added or updated unit tests for my change.

[contribution process]: https://git.io/fj2m9
[docs]: https://docs.crossplane.io/contribute/contribute

### CODE REVIEW

**Review by phisco — APPROVED** [review]
Good catch thanks!

File: fn.go [hunk 1]
```diff
@@ -134,9 +134,14 @@ func buildRequirements(in *v1beta1.Input, xr *resource.Composite) (*fnv1beta1.Re
 			for _, selector := range extraResource.Selector.MatchLabels {
 				switch selector.GetType() {
 				case v1beta1.ResourceSourceSelectorLabelMatcherTypeValue:
-					// TODO validate value not to be nil
```
Comment (phisco) [inline fn.go:137]: Looks like with this the complexity gets too high for the linter, can you add an ignore comment for gocyclo on the function signature above?

Comment (etesami) [reply fn.go:137]: I added the nolint comment. Please let me know if that's sufficient.
